# WAP  a program to input eight numbers from the user and display all the uniue numbers (once) ?

num = set()
s1 = int(input("Enter number  :"))
num.add(s1)
s2 = int(input("Enter number  :"))
num.add(s2)
s3 = int(input("Enter number  :"))
num.add(s3)
s4 = int(input("Enter number  :"))
num.add(s4)
s5 = int(input("Enter number  :"))
num.add(s5)
s6 = int(input("Enter number  :"))
num.add(s6)
s7 = int(input("Enter number  :"))
num.add(s7)
s8 = int(input("Enter number  :"))
num.add(s8)
print(num)
